kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:latest
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker build -t mavic .

- name: prepare
  image: python:3.10-slim
  commands:
  - pip install --upgrade pip wheel setuptools
  - pip install -r requirements.txt

- name: run_tests
  image: python:3.10-slim
  commands:
  - pip install -r requirements.txt
  - python setup.py install
  - pytest

- name: run_cov
  image: python:3.10-slim
  commands:
  - pip install -r requirements.txt
  - python setup.py install
  - pytest --cov=mavic --cov-report annotate

- name: run_mavic
  image: python:3.10-slim
  commands:
  - python setup.py install
  - python -m mavic

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
  