kind: pipeline
type: docker
name: default

steps:
- name: prepare1
  image: python:3.10-slim
  commands:
  - pip install --upgrade pip wheel setuptools

- name: prepare2
  image: python:3.10-slim
  commands:
  - pip install -r requirements.txt

- name: run_tests
  image: python:3.10-slim
  commands:
  - pip install -r requirements.txt
  - python setup.py install
  - pytest

- name: run_cov
  image: python:3.10-slim
  commands:
  - pip install -r requirements.txt
  - python setup.py install
  - pytest --cov=mavic --cov-report annotate

- name: run_mavic
  image: python:3.10-slim
  commands:
  - python setup.py install
  - python -m mavic
